#ifndef CONFIG_H
#define CONFIG_H

#define LARGURA_TELA 800
#define ALTURA_TELA 600
#define TAM_BLOCO 40
#define TOTAL_LINHAS 15
#define TOTAL_COLUNAS 20
#define LINHA_INICIAL_JOGADOR 13
#define COLUNA_INICIAL_JOGADOR 10
#define LARGURA_JOGADOR 30
#define ALTURA_JOGADOR 30
#define MARGEM_JOGADOR 5
#define PRIMEIRA_LINHA_RUA 5
#define ULTIMA_LINHA_RUA 9
#define ESPESSURA_BORDA_RUA 3
#define LARGURA_CARRO 70
#define ALTURA_CARRO 30
#define VELOCIDADE_CARRO 180
#define X_INICIAL_CARRO -80
#define Y_INICIAL_CARRO 280
#define X_INTERFACE 10
#define Y_SCORE 10
#define TAM_TEXTO_INTERFACE 18

#endif
